### ISSUE TITLE
Decide on database technology to be used

### ISSUE THREAD

**Issue by EoinMorganL00177775** [EoinMorganL00177775/Studio-Ghiblis-Movie-Maker#6]
The application will require a database that can be integrated easily into ASP.NET, and deployed either in another docker container or elsewhere that will be accessible for the application
Security must be considered, in addition to persistence, as the data must remain when the application is redeployed to allow for continuous integration and development

**Comment by L00177579** [comment]
I have experience using SQL but I would be unsure if this is overkill for this project. 
There's also another consideration on cost. So we need to be careful what we deploy.

**Comment by L00177579** [comment]
Additional:
Will we be doing any computation on the database side or strictly in C# (using LINQ)?

**Comment by EoinMorganL00177775** [comment]
@L00177579 Agreed, we will need to consider deployability and cost when choosing. In terms of interaction, I would say SQL would be good, don't think it would be overkill considering we want to show best practice, but perhaps we could use a framework to abstract away from the need for it. See my comment on CRUD ticket for details.
In terms of computation, I would say it is best to use LINQ in C# for computation and use the database purely as a data store, LINQ is much more readable and easier to implement, and also easier to make changes in than editing the database

**Comment by denism2022** [comment]
Can we close this issue? MariaDB was agreed and it’s ready to be used/tested.
